apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- service.yaml
- admission-controller.yaml
- scheduler.yaml

configMapGenerator:
- name: yunikorn-defaults
  namespace: yunikorn
  options:
    disableNameSuffixHash: true
    annotations:
      "helm.sh/resource-policy": "keep"
    labels:
      "app": "yunikorn"
      "chart": "yunikorn-1.6.1"
      "heritage": "Helm"
      "release": "yunikorn"
  files:
