apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
  labels:
    app: kube-prometheus-stack-admission-patch
    app.kubernetes.io/component: prometheus-operator-webhook
    app.kubernetes.io/instance: monitoring
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kube-prometheus-stack-prometheus-operator
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 69.3.2
    chart: kube-prometheus-stack-69.3.2
    heritage: Helm
    release: monitoring
  name: monitoring-kube-prometheus-admission-patch
  namespace: monitoring
spec:
  template:
    metadata:
      labels:
        app: kube-prometheus-stack-admission-patch
        app.kubernetes.io/component: prometheus-operator-webhook
        app.kubernetes.io/instance: monitoring
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: kube-prometheus-stack-prometheus-operator
        app.kubernetes.io/part-of: kube-prometheus-stack
        app.kubernetes.io/version: 69.3.2
        chart: kube-prometheus-stack-69.3.2
        heritage: Helm
        release: monitoring
      name: monitoring-kube-prometheus-admission-patch
    spec:
      containers:
      - args:
        - patch
        - --webhook-name=monitoring-kube-prometheus-admission
        - --namespace=monitoring
        - --secret-name=monitoring-kube-prometheus-admission
        - --patch-failure-policy=
        image: kind-registry:5000/registry.k8s.io/ingress-nginx/kube-webhook-certgen:v1.5.1
        imagePullPolicy: IfNotPresent
        name: patch
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
      restartPolicy: OnFailure
      securityContext:
        runAsGroup: 2000
        runAsNonRoot: true
        runAsUser: 2000
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: monitoring-kube-prometheus-admission
  ttlSecondsAfterFinished: 60
