apiVersion: v1
kind: Service
metadata:
  labels:
    app: kube-prometheus-stack-kube-etcd
    app.kubernetes.io/instance: monitoring
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 69.3.2
    chart: kube-prometheus-stack-69.3.2
    heritage: Helm
    jobLabel: kube-etcd
    release: monitoring
  name: monitoring-kube-prometheus-kube-etcd
  namespace: kube-system
spec:
  clusterIP: None
  ports:
  - name: http-metrics
    port: 2381
    protocol: TCP
    targetPort: 2381
  selector:
    component: etcd
  type: ClusterIP
