apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: volcano-admission
  name: volcano-admission
  namespace: volcano-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: volcano-admission
  template:
    metadata:
      labels:
        app: volcano-admission
    spec:
      containers:
      - args:
        - --enabled-admission=/jobs/mutate,/jobs/validate,/podgroups/mutate,/pods/validate,/pods/mutate,/queues/mutate,/queues/validate
        - --tls-cert-file=/admission.local.config/certificates/tls.crt
        - --tls-private-key-file=/admission.local.config/certificates/tls.key
        - --ca-cert-file=/admission.local.config/certificates/ca.crt
        - --admission-conf=/admission.local.config/configmap/volcano-admission.conf
        - --webhook-namespace=volcano-system
        - --webhook-service-name=volcano-admission-service
        - --enable-healthz=true
        - --logtostderr
        - --port=8443
        - -v=4
        - 2>&1
        image: kind-registry:5000/docker.io/volcanosh/vc-webhook-manager:v1.11.0
        imagePullPolicy: IfNotPresent
        name: admission
        volumeMounts:
        - mountPath: /admission.local.config/certificates
          name: admission-certs
          readOnly: true
        - mountPath: /admission.local.config/configmap
          name: admission-config
      priorityClassName: system-cluster-critical
      serviceAccount: volcano-admission
      volumes:
      - name: admission-certs
        secret:
          defaultMode: 420
          secretName: volcano-admission-secret
      - configMap:
          name: volcano-admission-configmap
        name: admission-config
